### ISSUE TITLE
Fail to read the correct file when calling compile_file

### ISSUE THREAD

**Issue by RedL0tus** [compass-rs/sass-rs#36]
It can be reproduced with the latest release with the in-tree example:

```log
➜  examples git:(30c99f1) RUST_BACKTRACE=1 cargo run --example compile_sass simple.sass
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `/home/kay/Documents/github/sass-rs/target/debug/examples/compile_sass simple.sass`
Compiling sass file: `simple.sass`.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Internal Error: File to read not found or unreadable: simple.sass\n"', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:390
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /rustc/6acbb5b65c06d82c867a94c54ce51dab4707ac61/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/6acbb5b65c06d82c867a94c54ce51dab4707ac61/src/libcore/result.rs:808
  10: compile_sass::main
             at examples/compile_sass.rs:12
  11: std::rt::lang_start::{{closure}}
             at /rustc/6acbb5b65c06d82c867a94c54ce51dab4707ac61/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  15: std::rt::lang_start
             at /rustc/6acbb5b65c06d82c867a94c54ce51dab4707ac61/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

It seems there is a mysterious `\n` in the file path while trying to compile.

**Comment by quininer** [comment]
try `cargo run --example compile_sass ./examples/simple.sass`.

**Comment by RedL0tus** [comment]
> try `cargo run --example compile_sass ./examples/simple.sass`.

hmmm I've tried that before, but right now it works... What the hug 😂
