### ISSUE TITLE
Failed to build under WSL

### ISSUE THREAD

**Issue by leotsarev** [compass-rs/sass-rs#76]
```
error: failed to run custom build command for `sass-sys v0.4.21`

Caused by:
  process didn't exit successfully: `/mnt/c/Users/leo/source/repos/leotsarev/zola/target/debug/build/sass-sys-9d68eb7e929d851e/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at '
  fs::copy(path, dst) failed with Operation not permitted (os error 1)
  ', /home/leotsarev/.cargo/registry/src/github.com-1ecc6299db9ec823/sass-sys-0.4.21/build.rs:46:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
     1: std::panicking::begin_panic_fmt
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
     2: build_script_build::cp_r
               at ./build.rs:46
     3: build_script_build::compile
               at ./build.rs:92
     4: build_script_build::main
               at ./build.rs:218
     5: core::ops::function::FnOnce::call_once
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Keats** [comment]
Eh building this library on Windows is annoying. I'm hoping https://github.com/connorskees/grass will replace it completely soon.
